server:
  port: 8080

spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:mem:emp_db
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        properties: 
          format-sql: true